name: Generate Changelog
description: Generate changelog and release notes using gptchangelog

inputs:
  OPENAI_API_KEY:
    required: true
  GH_TOKEN:
    required: true
  LERIAN_CI_CD_USER_GPG_KEY:
    required: true
  LERIAN_CI_CD_USER_GPG_KEY_PASSWORD:
    required: true
  LERIAN_CI_CD_USER_NAME:
    required: true
  LERIAN_CI_CD_USER_EMAIL:
    required: true
  LERIAN_STUDIO_MIDAZ_PUSH_BOT_APP_ID:
    required: true
  LERIAN_STUDIO_MIDAZ_PUSH_BOT_PRIVATE_KEY:
    required: true

permission:
  contents: write
  id-token: write
  packages: write

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - run: |
        python -m pip install --upgrade pip
        pip install gptchangelog
      shell: bash

    - run: |
        mkdir -p .gptchangelog
        echo "[gptchangelog]" > .gptchangelog/config.ini
        echo "openai = true" >> .gptchangelog/config.ini
        echo "[openai]" >> .gptchangelog/config.ini
        echo "api_key = ${OPENAI_API_KEY}" >> .gptchangelog/config.ini
        echo "model = gpt-4o" >> .gptchangelog/config.ini
        echo "max_context_tokens = 80000" >> .gptchangelog/config.ini
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}

    - run: |
        mkdir -p .gptchangelog/templates
        cat > .gptchangelog/templates/changelog_prompt.txt << 'EOF'
        # $project_name Changelog

        ## Release $next_version (Released on $current_date)

        ### What's New
        $commit_messages

        ### ✨ Features
        - Highlight new features added in this release.

        ### 🛠 Fixes
        - List bug fixes and improvements.

        ### 📚 Documentation
        - Summarize updates to documentation.

        ### 🚀 Improvements
        - Highlight performance or backend optimizations.

        ### ⚠️ Breaking Changes
        - List any breaking changes here.

        ### 🙌 Contributors
        - Acknowledge contributors for this release.
        EOF
      shell: bash

    - run: |
        echo "OPENAI_API_KEY=${OPENAI_API_KEY}" > .env
        git fetch --tags

        if git describe --tags --abbrev=0 --match "v*" HEAD >/dev/null 2>&1; then
          LAST_TAG=$(git describe --tags --abbrev=0 --match "v*" HEAD)

          if git describe --tags --abbrev=0 --match "v*" HEAD^ >/dev/null 2>&1; then
            PENULT_TAG=$(git describe --tags --abbrev=0 --match "v*" HEAD^)
            echo "🟢 Generating changelog from $PENULT_TAG to $LAST_TAG"
            gptchangelog generate --since "$PENULT_TAG" --to "$LAST_TAG" --output CHANGELOG.md
          else
            FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD)
            echo "🟡 First tag detected. Generating changelog from $FIRST_COMMIT to $LAST_TAG"
            gptchangelog generate --since "$FIRST_COMMIT" --to "$LAST_TAG" --output CHANGELOG.md
          fi

          # Exporting LAST_TAG to the environment
          echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV
        else
          FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD)
          echo "🔴 No tag detected. Generating changelog from $FIRST_COMMIT to HEAD"
          gptchangelog generate --since "$FIRST_COMMIT" --to HEAD --output CHANGELOG.md
          
          # Fallback for LAST_TAG
          echo "LAST_TAG=HEAD" >> $GITHUB_ENV
        fi
      
        echo "🧹 Cleaning up extra markdown blocks"
        sed -i '/^```/d' CHANGELOG.md
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
      
    - name: Replace version header
      run: |
        echo "📌 Replacing version header generated by gptchangelog"

        # Finds the line containing the first version header `## [vX.Y.Z] - ...`
        HEADER_LINE=$(grep -nE "^## \[v[0-9]+\.[0-9]+\.[0-9]+\] - " CHANGELOG.md | head -n 1 | cut -d: -f1)
        echo "📍 Header found on line: $HEADER_LINE"

        # Replaces exactly that line with the new version based on LAST_TAG
        sed -i "${HEADER_LINE}s|^.*|## [v${LAST_TAG//v/}] - $(date +%Y-%m-%d)|" CHANGELOG.md

        echo "✅ Line updated:"
        sed -n "${HEADER_LINE}p" CHANGELOG.md
      shell: bash
      env:
        LAST_TAG: ${{ env.LAST_TAG }}
    
    # - name: Replace version header
    #   run: |
    #     echo "📌 Substituindo cabeçalho da versão"
    #     sed -i "/^## \[v[0-9]\+\.[0-9]\+\.[0-9]\+\(-[a-zA-Z0-9.]\+\)\?\] - .*/c\## [v${LAST_TAG//v/}] - $(date +%Y-%m-%d)" CHANGELOG.md
    #     cat CHANGELOG.md
    #   shell: bash
    #   env:
    #     LAST_TAG: ${{ env.LAST_TAG }}

    - name: Replace version header
      run: |
        echo "📌 Replacing version header"
        sed -i "5s|^## \[v[0-9]\+\.[0-9]\+\.[0-9]\+\(-[a-zA-Z0-9.]\+\)\?\] - .*|## [v${LAST_TAG//v/}] - $(date +%Y-%m-%d)|" CHANGELOG.md
        cat CHANGELOG.md
      shell: bash
      env:
        LAST_TAG: ${{ env.LAST_TAG }}
    
    - run: |
        echo "OPENAI_API_KEY=${OPENAI_API_KEY}" > .env
        git fetch --tags

        # Checks if at least one tag exists
        if git describe --tags --abbrev=0 --match "v*" HEAD >/dev/null 2>&1; then
          LAST_TAG=$(git describe --tags --abbrev=0 --match "v*" HEAD)

          # Tries to get the previous tag
          if git describe --tags --abbrev=0 --match "v*" HEAD^ >/dev/null 2>&1; then
            PENULT_TAG=$(git describe --tags --abbrev=0 --match "v*" HEAD^)
            echo "🟢 Generating release notes from $PENULT_TAG to $LAST_TAG"
            gptchangelog generate --since "$PENULT_TAG" --to "$LAST_TAG" --output RELEASE_NOTES.md
          else
            FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD)
            echo "🟡 First tag detected. Generating release notes from $FIRST_COMMIT to $LAST_TAG"
            gptchangelog generate --since "$FIRST_COMMIT" --to "$LAST_TAG" --output RELEASE_NOTES.md
          fi

          echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV
        else
          FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD)
          echo "🔴 No tag detected. Generating release notes from $FIRST_COMMIT to HEAD"
          gptchangelog generate --since "$FIRST_COMMIT" --to HEAD --output RELEASE_NOTES.md
        fi
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
      
   
    - run: |
        # Captures the version header line
        HEADER_LINE=$(grep -n "^## \[v\?[0-9]\+\.[0-9]\+\.[0-9]\+\(-[a-zA-Z0-9.]\+\)\?\] - [0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}" RELEASE_NOTES.md | head -n1 | cut -d: -f1)

        # Checks if the line was found
        if [ -z "$HEADER_LINE" ]; then
          echo "Error: could not find version header in RELEASE_NOTES.md"
          exit 1
        fi

        # Displays the line number where the version header was found
        echo "📌 The version header line is: $HEADER_LINE"

        # Replaces the version header (with or without 'v' in the original)
        sed -i "${HEADER_LINE}s|^## \[v\?[0-9]\+\.[0-9]\+\.[0-9]\+\(-[a-zA-Z0-9.]\+\)\?\] - .*|## [v${LAST_TAG//v/}] - $(date +%Y-%m-%d)|" RELEASE_NOTES.md

        # Displays the file for confirmation
        cat RELEASE_NOTES.md
      shell: bash
      env:
        LAST_TAG: ${{ env.LAST_TAG }}
      
    - run: |
        gh release edit ${{ env.LAST_TAG }} --notes-file RELEASE_NOTES.md
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}

    - uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ inputs.LERIAN_CI_CD_USER_GPG_KEY }}
        passphrase: ${{ inputs.LERIAN_CI_CD_USER_GPG_KEY_PASSWORD }}
        git_committer_name: ${{ inputs.LERIAN_CI_CD_USER_NAME }}
        git_committer_email: ${{ inputs.LERIAN_CI_CD_USER_EMAIL }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true

    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ inputs.LERIAN_STUDIO_MIDAZ_PUSH_BOT_APP_ID }}
        private-key: ${{ inputs.LERIAN_STUDIO_MIDAZ_PUSH_BOT_PRIVATE_KEY }}
    
    - run: |
        BASE_BRANCH="${GITHUB_REF##*/}"
        BRANCH_NAME="release/update-changelog-${{ env.LAST_TAG }}"
        
        git checkout -b $BRANCH_NAME

        git add CHANGELOG.md
        git diff --cached --quiet || git commit -S -m "chore(release): Update CHANGELOG"

        # Merges the BASE_BRANCH into your branch, always prioritizing your version of the changelog
        git fetch origin "$BASE_BRANCH"
        git merge -X ours origin/"$BASE_BRANCH" --no-ff -m "Merge $BASE_BRANCH into ${BRANCH_NAME}" || {
          # If there is a merge conflict (e.g. ort doesn't resolve everything), force the resolution
          git checkout --ours CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "resolve conflict using ours strategy"
        }

        # Pushes the updated branch
        git push --force-with-lease origin $BRANCH_NAME

        # Checks if the PR already exists
        if ! gh pr view $BRANCH_NAME --base "$BASE_BRANCH" > /dev/null 2>&1; then
          gh pr create \
            --title "chore(release): Update CHANGELOG" \
            --body "Automatic changelog update for ${{ env.LAST_TAG }}" \
            --base "$BASE_BRANCH" \
            --head $BRANCH_NAME
        fi

        gh pr merge --merge --delete-branch || true
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      shell: bash
