name: Generate Changelog
description: Generate changelog and release notes using gptchangelog

inputs:
  OPENAI_API_KEY:
    required: true
  GH_TOKEN:
    required: true
  LERIAN_CI_CD_USER_GPG_KEY:
    required: true
  LERIAN_CI_CD_USER_GPG_KEY_PASSWORD:
    required: true
  LERIAN_CI_CD_USER_NAME:
    required: true
  LERIAN_CI_CD_USER_EMAIL:
    required: true

permission:
  contents: read
  id-token: write
  packages: write

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - run: |
        python -m pip install --upgrade pip
        pip install gptchangelog
      shell: bash

    - run: |
        mkdir -p .gptchangelog
        echo "[gptchangelog]" > .gptchangelog/config.ini
        echo "openai = true" >> .gptchangelog/config.ini
        echo "[openai]" >> .gptchangelog/config.ini
        echo "api_key = ${OPENAI_API_KEY}" >> .gptchangelog/config.ini
        echo "model = gpt-4o" >> .gptchangelog/config.ini
        echo "max_context_tokens = 80000" >> .gptchangelog/config.ini
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}

    - run: |
        mkdir -p .gptchangelog/templates
        cat > .gptchangelog/templates/changelog_prompt.txt << 'EOF'
        # $project_name Changelog

        ## Release $next_version (Released on $current_date)

        ### What's New
        $commit_messages

        ### ✨ Features
        - Highlight new features added in this release.

        ### 🛠 Fixes
        - List bug fixes and improvements.

        ### 📚 Documentation
        - Summarize updates to documentation.

        ### 🚀 Improvements
        - Highlight performance or backend optimizations.

        ### ⚠️ Breaking Changes
        - List any breaking changes here.

        ### 🙌 Contributors
        - Acknowledge contributors for this release.
        EOF
      shell: bash

    - run: |
        echo "OPENAI_API_KEY=${OPENAI_API_KEY}" > .env
        git fetch --tags

        if git describe --tags --abbrev=0 --match "v*" HEAD >/dev/null 2>&1; then
          LAST_TAG=$(git describe --tags --abbrev=0 --match "v*" HEAD)

          if git describe --tags --abbrev=0 --match "v*" HEAD^ >/dev/null 2>&1; then
            PENULT_TAG=$(git describe --tags --abbrev=0 --match "v*" HEAD^)
            echo "🟢 Gerando changelog de $PENULT_TAG até $LAST_TAG"
            gptchangelog generate --since "$PENULT_TAG" --to "$LAST_TAG" --output CHANGELOG.md
          else
            FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD)
            echo "🟡 Primeira tag detectada. Gerando changelog de $FIRST_COMMIT até $LAST_TAG"
            gptchangelog generate --since "$FIRST_COMMIT" --to "$LAST_TAG" --output CHANGELOG.md
          fi

          # Exportando LAST_TAG para o ambiente
          echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV
        else
          FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD)
          echo "🔴 Nenhuma tag detectada. Gerando changelog de $FIRST_COMMIT até HEAD"
          gptchangelog generate --since "$FIRST_COMMIT" --to HEAD --output CHANGELOG.md

          echo "🧹 Limpando blocos de markdown extras"
          sed -i '/^```/d' CHANGELOG.md
          
          # Fallback para LAST_TAG
          echo "LAST_TAG=HEAD" >> $GITHUB_ENV
        fi
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
      
      - name: Descobrir linha do cabeçalho da versão
        run: |
          HEADER_LINE=$(grep -n "^## \[v[0-9]\+\.[0-9]\+\.[0-9]\+\(-[a-zA-Z0-9.]\+\)\?\] - " CHANGELOG.md | head -n 1 | cut -d: -f1)
          echo "📍 Cabeçalho da versão encontrado na linha: $HEADER_LINE"
          echo "::set-output name=header_line::$HEADER_LINE"
        shell: bash
    
    # - name: Substituir cabeçalho da versão
    #   run: |
    #     echo "📌 Substituindo cabeçalho da versão"
    #     sed -i "/^## \[v[0-9]\+\.[0-9]\+\.[0-9]\+\(-[a-zA-Z0-9.]\+\)\?\] - .*/c\## [v${LAST_TAG//v/}] - $(date +%Y-%m-%d)" CHANGELOG.md
    #     cat CHANGELOG.md
    #   shell: bash
    #   env:
    #     LAST_TAG: ${{ env.LAST_TAG }}

    # - name: Substituir cabeçalho da versão
    #   run: |
    #     echo "📌 Substituindo cabeçalho da versão"
    #     sed -i "2s|^## \[v[0-9]\+\.[0-9]\+\.[0-9]\+\(-[a-zA-Z0-9.]\+\)\?\] - .*|## [v${LAST_TAG//v/}] - $(date +%Y-%m-%d)|" CHANGELOG.md
    #     cat CHANGELOG.md
    #   shell: bash
    #   env:
    #     LAST_TAG: ${{ env.LAST_TAG }}
    
    - run: |
        echo "OPENAI_API_KEY=${OPENAI_API_KEY}" > .env
        git fetch --tags

        # Verifica se existe ao menos uma tag
        if git describe --tags --abbrev=0 --match "v*" HEAD >/dev/null 2>&1; then
          LAST_TAG=$(git describe --tags --abbrev=0 --match "v*" HEAD)

          # Tenta obter a tag anterior
          if git describe --tags --abbrev=0 --match "v*" HEAD^ >/dev/null 2>&1; then
            PENULT_TAG=$(git describe --tags --abbrev=0 --match "v*" HEAD^)
            echo "🟢 Gerando release notes de $PENULT_TAG até $LAST_TAG"
            gptchangelog generate --since "$PENULT_TAG" --to "$LAST_TAG" --output RELEASE_NOTES.md
          else
            FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD)
            echo "🟡 Primeira tag detectada. Gerando release notes de $FIRST_COMMIT até $LAST_TAG"
            gptchangelog generate --since "$FIRST_COMMIT" --to "$LAST_TAG" --output RELEASE_NOTES.md
          fi

          echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV
        else
          FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD)
          echo "🔴 Nenhuma tag detectada. Gerando release notes de $FIRST_COMMIT até HEAD"
          gptchangelog generate --since "$FIRST_COMMIT" --to HEAD --output RELEASE_NOTES.md
        fi
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
      
   
    - run: |
        # Captura a linha do cabeçalho da versão
        HEADER_LINE=$(grep -n "^## \[v\?[0-9]\+\.[0-9]\+\.[0-9]\+\(-[a-zA-Z0-9.]\+\)\?\] - [0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}" RELEASE_NOTES.md | head -n1 | cut -d: -f1)

        # Verifica se a linha foi encontrada
        if [ -z "$HEADER_LINE" ]; then
          echo "Erro: não foi possível encontrar o cabeçalho da versão em RELEASE_NOTES.md"
          exit 1
        fi

        # Exibe o número da linha onde o cabeçalho da versão foi encontrado
        echo "📌 A linha do cabeçalho da versão é: $HEADER_LINE"

        # Substitui o cabeçalho da versão (com ou sem 'v' no original)
        sed -i "${HEADER_LINE}s|^## \[v\?[0-9]\+\.[0-9]\+\.[0-9]\+\(-[a-zA-Z0-9.]\+\)\?\] - .*|## [v${LAST_TAG//v/}] - $(date +%Y-%m-%d)|" RELEASE_NOTES.md

        # Exibe o arquivo para confirmação
        cat RELEASE_NOTES.md
      shell: bash
      env:
        LAST_TAG: ${{ env.LAST_TAG }}
      
    - run: |
        gh release edit ${{ env.LAST_TAG }} --notes-file RELEASE_NOTES.md
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}

    - uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ inputs.LERIAN_CI_CD_USER_GPG_KEY }}
        passphrase: ${{ inputs.LERIAN_CI_CD_USER_GPG_KEY_PASSWORD }}
        git_committer_name: ${{ inputs.LERIAN_CI_CD_USER_NAME }}
        git_committer_email: ${{ inputs.LERIAN_CI_CD_USER_EMAIL }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true

    - run: |
        git config --global user.name "${{ inputs.LERIAN_CI_CD_USER_NAME }}"
        git config --global user.email "${{ inputs.LERIAN_CI_CD_USER_EMAIL }}"
      shell: bash

    - run: |
        git add CHANGELOG.md
        git diff --cached --quiet || (git commit -S -m "chore(release): Update CHANGELOG" && git push)
      shell: bash
